"""Word-trie completion bias layer.

Given `state.word_buffer` (the letters written since the last non-letter),
if the buffer is a prefix of one or more common English/Shakespearean
words, bias the distribution toward the letters (and word-ending
characters) that would complete those words. The longer the prefix, the
more confident the completion bias.

All knowledge here comes from prior knowledge of common Shakespearean
vocabulary. No corpus statistics.
"""

from __future__ import annotations

from ..vocab import VOCAB_INDEX, VOCAB_SIZE

# A list of common Shakespearean / Early Modern English words (lowercased).
# Mixed with common modern English frequent words. Apostrophes are
# represented literally.
_WORDS: tuple[str, ...] = (
    # --- frequent English function words ---
    "the", "and", "to", "of", "a", "in", "that", "is", "was", "for",
    "on", "with", "as", "at", "by", "this", "it", "be", "but", "or",
    "an", "if", "so", "not", "are", "from", "were", "been", "have",
    "has", "had", "do", "did", "does", "will", "would", "should",
    "could", "may", "might", "shall", "can", "must", "than", "though",
    "there", "here", "them", "these", "those", "such", "no", "yes",
    "all", "any", "some", "each", "every", "both", "either", "neither",
    "more", "most", "less", "much", "many", "few",
    # --- pronouns & possessives ---
    "i", "me", "my", "mine", "myself",
    "you", "your", "yours", "yourself",
    "he", "him", "his", "himself",
    "she", "her", "hers", "herself",
    "we", "us", "our", "ours", "ourselves",
    "they", "them", "their", "theirs", "themselves",
    "it", "its", "itself", "one", "ones",
    # --- Shakespeare archaic pronouns/verbs ---
    "thou", "thee", "thy", "thine", "thyself",
    "ye", "art", "hath", "doth", "dost", "hast",
    "shalt", "wilt", "wouldst", "shouldst", "couldst",
    "didst", "canst", "mayst", "wert", "prithee", "methinks",
    "yond", "yonder", "hither", "thither", "whither",
    "hence", "thence", "whence",
    # --- Common verbs (base + common inflections) ---
    "go", "goes", "going", "gone", "went",
    "come", "comes", "coming", "came",
    "know", "knows", "knew", "known",
    "think", "thinks", "thinking", "thought",
    "say", "says", "said", "saying",
    "see", "sees", "seen", "saw", "seeing",
    "make", "makes", "made", "making",
    "take", "takes", "took", "taken", "taking",
    "tell", "tells", "told", "telling",
    "give", "gives", "gave", "given", "giving",
    "find", "finds", "found", "finding",
    "leave", "leaves", "left", "leaving",
    "bring", "brings", "brought", "bringing",
    "hold", "holds", "held", "holding",
    "speak", "speaks", "spoke", "spoken", "speaking",
    "stand", "stands", "stood", "standing",
    "hear", "hears", "heard", "hearing",
    "keep", "keeps", "kept", "keeping",
    "let", "lets", "letting",
    "set", "sets", "setting",
    "run", "runs", "ran", "running",
    "sit", "sits", "sat", "sitting",
    "work", "works", "worked", "working",
    "play", "plays", "played", "playing",
    "move", "moves", "moved", "moving",
    "live", "lives", "lived", "living",
    "love", "loves", "loved", "loving", "lovely",
    "like", "likes", "liked", "likely",
    "want", "wants", "wanted",
    "need", "needs", "needed",
    "feel", "feels", "felt", "feeling",
    "look", "looks", "looked", "looking",
    "seem", "seems", "seemed",
    "show", "shows", "showed", "shown", "showing",
    "turn", "turns", "turned", "turning",
    "seek", "seeks", "sought", "seeking",
    "mean", "means", "meant", "meaning",
    "call", "calls", "called", "calling",
    "lie", "lies", "lay", "lying",
    "die", "dies", "died", "dying",
    "rise", "rises", "rose", "risen", "rising",
    "fall", "falls", "fell", "fallen", "falling",
    "fight", "fights", "fought", "fighting",
    "meet", "meets", "met", "meeting",
    "grant", "grants", "granted",
    "follow", "follows", "followed", "following",
    "beg", "begs", "begged", "begging",
    "kneel", "kneels", "knelt",
    "swear", "swears", "swore", "sworn", "swearing",
    "curse", "curses", "cursed", "cursing",
    "bless", "blesses", "blessed", "blessing",
    "forgive", "forgives", "forgave", "forgiven",
    "lose", "loses", "lost", "losing",
    "win", "wins", "won", "winning",
    "kill", "kills", "killed", "killing",
    "slay", "slays", "slew", "slain", "slaying",
    "weep", "weeps", "wept", "weeping",
    "cry", "cries", "cried", "crying",
    "laugh", "laughs", "laughed", "laughing",
    "sigh", "sighs", "sighed", "sighing",
    "sleep", "sleeps", "slept", "sleeping",
    "wake", "wakes", "woke", "waking",
    "dream", "dreams", "dreamed", "dreaming",
    "remember", "remembers", "remembered",
    "forget", "forgets", "forgot", "forgetting",
    "write", "writes", "wrote", "written",
    "read", "reads", "reading",
    "hope", "hopes", "hoped",
    "wish", "wishes", "wished",
    "dare", "dares", "dared",
    "fear", "fears", "feared",
    "deny", "denies", "denied",
    "confess", "confesses", "confessed",
    "marry", "marries", "married",
    "part", "parts", "parted",
    "depart", "departs", "departed",
    "return", "returns", "returned",
    "arrive", "arrives", "arrived",
    "enter", "enters", "entered", "entering",
    "exit", "exits", "exited",
    "pass", "passes", "passed", "passing",
    "let", "let's",
    # --- Shakespeare lexicon ---
    "lord", "lords", "lady", "ladies", "master", "masters",
    "mistress", "sir", "madam", "king", "kings", "queen", "queens",
    "prince", "princes", "princess", "duke", "dukes", "duchess",
    "earl", "earls", "count", "friar", "friars", "nurse", "nurses",
    "knight", "knights", "knave", "knaves", "fool", "fools",
    "villain", "villains", "rogue", "rogues", "wretch", "coward",
    "tyrant", "traitor", "murderer", "ghost", "ghosts", "spirit", "spirits",
    "witch", "witches", "god", "gods", "angel", "angels",
    "devil", "devils",
    "gentle", "gentleman", "gentlemen", "noble", "noblest", "nobler",
    "valiant", "fair", "fairest", "fairer", "sweet", "sweetest",
    "dear", "dearest", "dearer", "kind", "kindest", "kinder",
    "true", "truth", "false", "falsehood", "good", "goodness",
    "bad", "wicked", "great", "greater", "greatest", "small", "smaller",
    "young", "younger", "old", "older", "elder", "eldest",
    "new", "brave", "bravest", "braver", "cruel", "cruelty",
    "holy", "holiest", "sacred", "mortal", "immortal", "divine",
    "hollow", "royal", "humble", "honest", "honour", "honoured",
    "disgrace", "shame", "ashamed", "shameful",
    # --- body/nature ---
    "heart", "hearts", "soul", "souls", "mind", "minds",
    "head", "heads", "hand", "hands", "eye", "eyes",
    "face", "faces", "blood", "tongue", "tongues", "lips",
    "arm", "arms", "foot", "feet", "hair", "breath",
    "tear", "tears", "smile", "smiles", "voice", "voices",
    "life", "lives", "death", "deaths",
    "love", "hate", "fear", "hope", "dream", "dreams",
    "grief", "joy", "sorrow", "sorrows", "peace", "war",
    "time", "times", "day", "days", "night", "nights",
    "morn", "morning", "eve", "evening", "hour", "hours",
    "year", "years", "month", "months", "week", "weeks",
    "world", "worlds", "heaven", "heavens", "earth", "earths",
    "hell", "sky", "skies", "sun", "moon", "star", "stars",
    "sea", "seas", "land", "lands", "fire", "fires", "air",
    "water", "waters", "river", "rivers", "wind", "winds",
    "storm", "storms", "rain", "snow", "light", "lights",
    "dark", "darkness", "shadow", "shadows",
    "flower", "flowers", "rose", "roses", "thorn", "thorns",
    "sword", "swords", "crown", "crowns", "throne", "thrones",
    "court", "courts", "castle", "castles",
    "house", "houses", "home", "homes", "field", "fields",
    "tomb", "tombs", "grave", "graves", "cross", "crosses",
    "gold", "silver", "jewel", "jewels", "treasure",
    # --- adverbs / connectors / sentence starters ---
    "now", "then", "here", "there", "where", "when", "why", "how",
    "who", "what", "which", "whom", "whose",
    "before", "after", "between", "within", "without", "against",
    "through", "throughout", "upon", "unto", "until", "till",
    "about", "above", "below", "beneath", "beyond", "around",
    "among", "amongst", "amidst", "amid",
    "anon", "yet", "still", "ever", "never", "always",
    "oft", "often", "seldom", "rarely", "sometimes",
    "perhaps", "perchance", "surely", "truly", "indeed", "forsooth",
    "verily", "belike", "haply", "marry", "faith", "sooth", "troth",
    "alack", "alas", "ay", "aye", "nay", "yea", "well", "why",
    "fie", "pish", "tut", "hark", "lo", "behold",
    "therefore", "thereby", "thereof", "thereto", "herein", "herein",
    "whereby", "whereof", "wherein", "wheresoever",
    # --- Contractions (handled with apostrophe in buffer) ---
    "'tis", "'twas", "'twere", "'twould", "'gainst", "'tisn't",
    "o'er", "e'er", "ne'er", "'em", "'mongst",
    "i'll", "you'll", "he'll", "she'll", "we'll", "they'll",
    "i've", "you've", "we've", "they've",
    "i'd", "you'd", "he'd", "she'd", "we'd", "they'd",
    "i'm", "you're", "we're", "they're", "he's", "she's", "it's",
    "don't", "doesn't", "didn't", "won't", "wouldn't", "shouldn't",
    "can't", "cannot", "couldn't", "isn't", "aren't", "wasn't",
    "weren't", "hasn't", "haven't", "hadn't",
    "'s", "'d", "'ll", "'ve", "'re", "'t", "'m",
    # --- Address / exclamation ---
    "hello", "farewell", "adieu", "welcome", "pray", "prithee",
    "friend", "friends", "foe", "foes", "enemy", "enemies",
    "brother", "brothers", "sister", "sisters",
    "father", "fathers", "mother", "mothers",
    "son", "sons", "daughter", "daughters",
    "child", "children", "man", "men", "woman", "women",
    "boy", "boys", "girl", "girls",
    "lad", "lads", "lass", "lasses",
    "fellow", "fellows", "soldier", "soldiers",
    "servant", "servants", "page", "pages",
    "messenger", "messengers", "herald",
    # --- Verse fillers ---
    "oh", "ah", "o",
    # --- Numbers ---
    "one", "two", "three", "four", "five", "six", "seven",
    "eight", "nine", "ten", "hundred", "thousand",
    "first", "second", "third", "last",
    # --- Adjectives ---
    "beautiful", "ugly", "tall", "short", "long", "quick", "slow",
    "strong", "weak", "rich", "poor", "happy", "sad", "angry",
    "gentle", "rough", "hard", "soft", "warm", "cold",
    "full", "empty", "deep", "high", "low", "near", "far",
    "wise", "foolish", "mad", "sane", "bold", "timid",
    "pale", "bright", "dull", "keen", "sharp", "blunt",
    # --- Misc useful ---
    "yes", "nothing", "something", "anything", "everything",
    "none", "nobody", "somebody", "anybody", "everybody",
    "am", "be", "been", "being",
    # --- extended Shakespearean vocabulary ---
    "aught", "nought", "naught", "ought", "methought", "whilst",
    "amongst", "peradventure", "perchance", "forsooth", "sooth",
    "tarry", "tarried", "tarries", "tarrying",
    "whereupon", "hereupon", "thereupon", "wherefore",
    "again", "against", "once", "twice", "thrice",
    "cannot", "cannotsay", "nevertheless", "notwithstanding",
    "answer", "answers", "answered", "answering",
    "question", "questions", "questioned",
    "believe", "believes", "believed", "belief",
    "understand", "understands", "understood", "understanding",
    "become", "becomes", "became", "becoming",
    "cause", "causes", "caused", "causing",
    "matter", "matters", "mattered",
    "reason", "reasons", "reasoned",
    "consider", "considers", "considered", "considering",
    "remove", "removes", "removed", "removing",
    "change", "changes", "changed", "changing",
    "try", "tries", "tried", "trying",
    "place", "places", "placed", "placing",
    "point", "points", "pointed",
    "offer", "offers", "offered",
    "appear", "appears", "appeared", "appearing",
    "happen", "happens", "happened",
    "continue", "continues", "continued",
    "remember", "remembered", "remembrance",
    "suppose", "supposes", "supposed",
    "promise", "promises", "promised",
    "wonder", "wonders", "wondered", "wonderful", "wondrous",
    "attend", "attends", "attended", "attendant", "attendants",
    "command", "commands", "commanded", "commandment",
    "receive", "receives", "received", "receiving",
    "present", "presents", "presented", "presently",
    "prove", "proves", "proved", "proven", "proving", "proof",
    "power", "powers", "powerful",
    "person", "persons", "personal",
    "word", "words", "worded",
    "sound", "sounds", "sounded", "sounding",
    "spirit", "spirits",
    "mind", "minds", "minded",
    "faith", "faithful", "faithless",
    "fortune", "fortunes", "fortunate",
    "virtue", "virtues", "virtuous",
    "pleasure", "pleasures", "pleased", "pleasing", "please",
    "patience", "patient", "impatient",
    "courage", "courageous",
    "ancient", "ancients",
    "modern", "moderns",
    "nature", "natural", "natures",
    "trouble", "troubles", "troubled", "troubling",
    "danger", "dangers", "dangerous",
    "stranger", "strangers", "strange", "strangely",
    "perfect", "perfectly", "perfection",
    "content", "contents", "contented", "contentment",
    "conclude", "concluded", "conclusion",
    "certain", "certainly", "certainty", "uncertain",
    "enough", "rough", "through", "though", "thorough",
    "thought", "thoughts",
    "fair", "fairly", "unfair",
    "clear", "clearly", "clearness",
    "wise", "wisely", "wisdom",
    "chief", "chiefly", "chieftain",
    "honour", "honours", "honoured", "honourable", "dishonour",
    "shame", "shames", "shamed", "shameful", "shameless",
    "praise", "praises", "praised",
    "pray", "prays", "prayed", "prayer", "prayers",
    "heaven", "heavens", "heavenly",
    "voice", "voices",
    "dark", "darkly",
    "bright", "brightly",
    "sweet", "sweetly", "sweetness",
    "bitter", "bitterly", "bitterness",
    "warm", "warmly", "warmth",
    "deep", "deeply", "deepest",
    "light", "lights", "lighted", "lightly",
    "heavy", "heavier", "heaviest",
    "right", "rights", "righteous",
    "left", "lefts",
    "next", "nextly",
    "very", "verily",
    "almost", "already", "although", "altogether",
    "among", "amongst", "amid", "amidst",
    "because", "beside", "besides", "behind",
    "between", "beyond", "beneath", "below", "above",
    "within", "without", "withal", "whereof",
    "upon", "unto", "until", "till", "while",
    "enter", "exit",
    "hark", "lo",
    "stay", "stays", "stayed", "staying",
    "wait", "waits", "waited",
    "gentle", "gentler", "gentlest",
    "please", "pleasure",
    "silent", "silently", "silence",
    "noble", "nobles", "nobleman",
    "common", "commons",
    "country", "countries", "countryman",
    "people", "peoples",
    "city", "cities", "citizen", "citizens",
    "Rome", "Roman", "Romans",
    "France", "French",
    "England", "English",
    "Italy", "Italian",
    "nature", "nation", "nations",
    "ever", "never", "forever",
    "else", "elsewhere",
    "however", "whenever", "wherever", "whatever", "whoever", "whichever",
    "once", "hence",
    "this", "that", "these", "those",
    "here", "there", "where", "everywhere", "anywhere", "somewhere", "nowhere",
    "well", "good", "better", "best", "ill", "worse", "worst",
    # --- more common Shakespearean words ---
    "even", "evenly", "odd", "oddly",
    "whole", "wholly",
    "half", "halves",
    "round", "rounds", "rounded", "roundly",
    "alone", "along", "aloud",
    "afraid", "aside", "abroad", "apart", "across",
    "asleep", "awake", "aware", "away", "awhile",
    "behold", "beholds", "beheld", "beholding",
    "beware", "below", "beloved",
    "begin", "begins", "began", "begun", "beginning",
    "break", "breaks", "broke", "broken", "breaking",
    "burn", "burns", "burned", "burnt", "burning",
    "build", "builds", "built", "building",
    "buy", "buys", "bought", "buying",
    "choose", "chooses", "chose", "chosen", "choosing",
    "catch", "catches", "caught", "catching",
    "dance", "dances", "danced", "dancing",
    "draw", "draws", "drew", "drawn", "drawing",
    "drink", "drinks", "drank", "drunk", "drinking",
    "drive", "drives", "drove", "driven", "driving",
    "eat", "eats", "ate", "eaten", "eating",
    "fly", "flies", "flew", "flown", "flying",
    "grow", "grows", "grew", "grown", "growing",
    "hide", "hides", "hid", "hidden", "hiding",
    "hit", "hits", "hitting",
    "hurt", "hurts", "hurting",
    "join", "joins", "joined", "joining",
    "learn", "learns", "learned", "learnt", "learning",
    "pay", "pays", "paid", "paying",
    "put", "puts", "putting",
    "ride", "rides", "rode", "ridden", "riding",
    "ring", "rings", "rang", "rung",
    "send", "sends", "sent", "sending",
    "shut", "shuts", "shutting",
    "sing", "sings", "sang", "sung", "singing",
    "spend", "spends", "spent", "spending",
    "steal", "steals", "stole", "stolen", "stealing",
    "strike", "strikes", "struck", "striking",
    "swim", "swims", "swam", "swum", "swimming",
    "teach", "teaches", "taught", "teaching",
    "throw", "throws", "threw", "thrown", "throwing",
    "understand", "understands", "understood", "understanding",
    "wear", "wears", "wore", "worn", "wearing",
    "written", "writing",
    # Adjectives/intensifiers
    "such", "enough", "only", "quite", "rather", "little", "lot",
    "every", "any", "many", "much", "several", "various",
    "nearly", "entirely", "exactly", "completely", "totally",
    "simply", "merely", "solely",
    # More proper nouns (common in Shakespeare)
    "Caesar", "Brutus", "Cassius", "Antony", "Cleopatra", "Marcus",
    "Romeo", "Juliet", "Mercutio", "Benvolio", "Tybalt", "Paris",
    "Nurse", "Capulet", "Montague", "Friar", "Laurence", "Verona",
    "Hamlet", "Ophelia", "Claudius", "Gertrude", "Polonius",
    "Laertes", "Horatio", "Denmark", "Elsinore",
    "Macbeth", "Banquo", "Duncan", "Malcolm", "Scotland",
    "Othello", "Desdemona", "Iago", "Cassio", "Venice",
    "Lear", "Cordelia", "Regan", "Goneril", "Edmund", "Edgar",
    "Caius", "Marcius", "Coriolanus", "Menenius", "Aufidius", "Volumnia",
    "Prospero", "Miranda", "Caliban", "Ariel", "Ferdinand",
    "Portia", "Bassanio", "Shylock", "Antonio", "Lorenzo", "Jessica",
    "Benedick", "Beatrice", "Claudio", "Hero", "Don",
    "Rosalind", "Orlando", "Oliver", "Jaques",
    "Petruchio", "Katharina", "Bianca", "Baptista",
    "Titania", "Oberon", "Puck", "Bottom", "Theseus", "Hippolyta",
    "Helena", "Hermia", "Lysander", "Demetrius",
    "Viola", "Orsino", "Sebastian", "Malvolio", "Sir", "Toby",
    "Henry", "Richard", "Edward", "George", "Margaret",
    "York", "Lancaster", "Plantagenet", "Warwick", "Gloucester",
    "Clarence", "Buckingham", "Bolingbroke", "Northumberland",
    "Hotspur", "Falstaff", "Hal", "Pistol", "Nym", "Bardolph",
    # Commonly-seen simple words
    "only", "just", "maybe", "really", "truly", "surely",
    "today", "tomorrow", "yesterday", "tonight",
    "soon", "late", "early",
    "yes", "no", "maybe",
    "hello", "goodbye", "thanks",
    "well", "okay",
    "o'clock", "e'en",
    # --- archaic Shakespearean specifics ---
    "anon", "sirrah", "beshrew", "zounds",
    "quoth", "betwixt", "spake", "saith",
    "alas", "ado",
    # Body/emotion words
    "embrace", "embraces", "embraced",
    "kiss", "kisses", "kissed",
    "touch", "touches", "touched",
    "tremble", "trembles", "trembled", "trembling",
    "shake", "shakes", "shook", "shaken",
    "whisper", "whispers", "whispered",
    "mourn", "mourns", "mourned", "mourning",
    "grieve", "grieves", "grieved", "grieving",
    "rejoice", "rejoices", "rejoiced",
    "conquer", "conquers", "conquered",
    "surrender", "surrenders",
    "yield", "yields", "yielded",
    "escape", "escapes", "escaped",
    # Setting/objects
    "chamber", "chambers", "hall", "halls",
    "tower", "towers", "gate", "gates", "wall", "walls",
    "field", "fields", "forest", "forests",
    "wood", "woods", "tree", "trees", "leaf", "leaves",
    "hill", "hills", "mountain", "mountains",
    "valley", "valleys",
    "shore", "shores", "bank", "banks",
    "ship", "ships", "sail", "sails",
    "wave", "waves", "tide", "tides",
    "cloud", "clouds",
    # Numbers and quantities
    "eleven", "twelve", "twenty", "thirty", "forty", "fifty",
    # More connective words
    "whence", "whither",
    # --- Extended common Shakespearean / Early Modern English vocabulary ---
    # More verbs (inflected forms)
    "bid", "bids", "bade", "bidden", "bidding",
    "forbid", "forbids", "forbade",
    "grow", "grown", "growing", "growth",
    "seem", "seemed", "seeming",
    "hang", "hangs", "hung", "hanged", "hanging",
    "bind", "binds", "bound", "binding",
    "blow", "blows", "blew", "blown", "blowing",
    "burst", "bursts", "bursting",
    "cast", "casts", "casting",
    "creep", "creeps", "crept",
    "deal", "deals", "dealt",
    "dig", "digs", "dug",
    "freeze", "freezes", "froze", "frozen",
    "grind", "grinds", "ground",
    "lend", "lends", "lent", "lending",
    "mistake", "mistakes", "mistook", "mistaken",
    "rend", "rends", "rent",
    "shed", "sheds", "shedding",
    "shoot", "shoots", "shot", "shooting",
    "shrink", "shrinks", "shrank", "shrunk",
    "spread", "spreads", "spreading",
    "stick", "sticks", "stuck",
    "sting", "stings", "stung", "stinging",
    "strive", "strives", "strove", "striven",
    "wind", "winds", "wound", "winding",
    "wring", "wrings", "wrung",
    "plant", "plants", "planted", "planting",
    "plead", "pleads", "pleaded", "pleading",
    "drown", "drowns", "drowned", "drowning",
    "faint", "faints", "fainted", "fainting",
    "praise", "praises", "praised", "praising",
    "punish", "punishes", "punished",
    "reward", "rewards", "rewarded",
    "mock", "mocks", "mocked", "mocking",
    "scorn", "scorns", "scorned", "scornful",
    "pity", "pities", "pitied", "pitying",
    "pardon", "pardons", "pardoned",
    "spare", "spares", "spared", "sparing",
    "starve", "starves", "starved", "starving",
    "banish", "banishes", "banished",
    "rule", "rules", "ruled", "ruling",
    "reign", "reigns", "reigned",
    "judge", "judges", "judged", "judgment",
    "avenge", "avenges", "avenged",
    "betray", "betrays", "betrayed",
    "seize", "seizes", "seized",
    "slumber", "slumbers", "slumbered",
    "behold", "beholds", "beheld", "beholding",
    "appear", "appears", "appeared", "appearing",
    "vanish", "vanishes", "vanished",
    "fly", "flies", "flew", "flown",
    "seek", "sought", "seeking",
    "drink", "drinks", "drank", "drunk",
    # More adjectives
    "bare", "barren", "blessed", "bold", "bright",
    "busy", "calm", "certain", "chaste", "choice", "clean",
    "clear", "close", "common", "cruel", "damn", "damned",
    "dead", "deaf", "deep", "dim", "dire", "dry",
    "eager", "easy", "empty", "equal", "even", "evil",
    "excellent", "faint", "fairest", "famous", "fat", "fell",
    "fierce", "fine", "firm", "fit", "fond", "free",
    "frank", "fresh", "full", "furious", "gentle", "glad",
    "golden", "grand", "grave", "green", "grim", "happy",
    "harsh", "hateful", "heavy", "hideous", "hollow",
    "horrid", "humble", "idle", "innocent", "just",
    "keen", "lame", "lean", "light", "loud", "loose",
    "low", "mad", "meek", "mere", "mighty", "mild",
    "monstrous", "nice", "nimble", "patient", "pale",
    "plain", "plump", "pretty", "proud", "pure", "quiet",
    "rare", "raw", "ready", "red", "rich", "ripe",
    "rough", "rude", "sad", "safe", "scarce", "secret",
    "sharp", "shy", "silent", "single", "slender", "slim",
    "slow", "solid", "sore", "sour", "strict", "strong",
    "stubborn", "sudden", "supreme", "tame", "tart", "tender",
    "thick", "tight", "timid", "tired", "tough", "tranquil",
    "unhappy", "vain", "vast", "vile", "weary", "wet",
    "white", "whole", "wild", "wise", "worthy", "wretched",
    # More nouns (common)
    "act", "acts", "action", "actions",
    "age", "ages", "air", "anger", "art",
    "beauty", "beast", "beasts", "bed", "beds",
    "bell", "bells", "bird", "birds", "body", "bodies",
    "book", "books", "bond", "bonds", "boy", "bread",
    "bride", "brides", "bridegroom", "bridge", "bridges",
    "burden", "burdens", "care", "cares",
    "cheek", "cheeks", "child", "children",
    "church", "churches", "coast", "coasts",
    "coin", "coins", "course", "courses",
    "creature", "creatures", "crime", "crimes",
    "cup", "cups", "danger", "dangers",
    "debt", "debts", "deed", "deeds", "desire", "desires",
    "dinner", "doctor", "door", "doors", "dust",
    "end", "ends", "error", "errors", "fact", "facts",
    "faith", "fame", "farm", "fate", "fates",
    "father", "fathers", "favour", "favours", "feast", "feasts",
    "feather", "feathers", "fellow", "fellows",
    "fever", "fevers", "fiend", "fiends",
    "figure", "figures", "floor", "floors", "form", "forms",
    "friend", "friends", "fruit", "fruits", "game", "games",
    "garden", "gardens", "gift", "gifts", "girl", "girls",
    "glory", "glories", "goddess", "goddesses",
    "grace", "graces", "ground", "grounds",
    "guilt", "guilts", "guise",
    "half", "halt", "harm", "harms", "hate", "head",
    "health", "hill", "hills", "home", "homes",
    "hope", "hopes", "horn", "horns", "horror", "horrors",
    "horse", "horses", "host", "hosts", "house", "houses",
    "husband", "husbands", "image", "images", "injury", "injuries",
    "issue", "issues", "jest", "jests", "journey", "journeys",
    "judge", "judges", "labour", "labours",
    "lamp", "lamps", "letter", "letters", "liberty",
    "line", "lines", "liver", "look", "looks",
    "lover", "lovers", "lot", "lots", "loss", "losses",
    "luck", "luxury", "madam", "maid", "maids",
    "maiden", "maidens", "manner", "manners", "map", "maps",
    "mark", "marks", "mass", "masses", "match", "matches",
    "maze", "meat", "meats", "merchant", "merchants",
    "mercy", "mercies", "message", "messages",
    "mirror", "mirrors", "mischief", "miser", "misery",
    "mistress", "mistresses", "money", "monster", "monsters",
    "mountain", "mountains", "music",
    "name", "names", "neck", "necks", "news",
    "noise", "noises", "nose", "notes",
    "oath", "oaths", "office", "offices", "order", "orders",
    "pair", "pairs", "palace", "palaces", "pale", "paper",
    "park", "parks", "passage", "passion", "passions",
    "path", "paths", "pause", "pawn", "peril",
    "phrase", "phrases", "pick", "pile", "pillar",
    "pipe", "pipes", "pistol", "place", "places",
    "plague", "plagues", "planet", "plant",
    "play", "plays", "pleasure", "poem", "poems", "poet",
    "poets", "point", "points", "poison", "poisons",
    "pole", "pool", "pools", "pope",
    "price", "prices", "pride", "prison", "prisons",
    "prize", "profit", "program", "purple", "purpose",
    "rag", "rage", "rain", "rains", "ransom",
    "reason", "reasons", "record", "reign", "remainder",
    "rest", "rests", "return", "returns",
    "right", "rights", "ring", "rings",
    "road", "roads", "rock", "rocks", "root", "roots",
    "room", "rooms", "rule", "rules", "sail", "sails",
    "saint", "saints", "salt", "sand", "seat", "seats",
    "second", "seconds", "season", "seasons",
    "sense", "senses", "sentence", "sentences",
    "service", "services", "sex", "sexes", "sheep",
    "shelter", "shield", "shields", "shift", "shirt",
    "shock", "shocks", "shoe", "shoes", "sign", "signs",
    "silk", "silks", "silver", "silvers",
    "sin", "sins", "sir", "sister", "sisters",
    "size", "sizes", "skin", "skins", "sky",
    "slave", "slaves", "smile", "smiles", "smoke",
    "snake", "snakes", "song", "songs",
    "speech", "speeches", "spite", "sport", "sports",
    "spring", "springs", "staff", "stage", "stages",
    "state", "states", "step", "steps", "stock",
    "stone", "stones", "stop", "stops", "store", "stores",
    "story", "stories", "street", "streets", "strength",
    "strife", "stroke", "strokes", "study", "studies",
    "style", "styles", "success", "successes",
    "suit", "suits", "summer", "summers",
    "sun", "suns", "supper", "surface",
    "surprise", "sway", "tale", "tales", "task", "tasks",
    "taste", "tastes", "tax", "taxes",
    "temple", "temples", "test", "tests",
    "thief", "thieves", "thing", "things",
    "throat", "throats", "throne", "thrones",
    "tide", "tides", "title", "titles",
    "tomb", "tombs", "tone", "tones", "top", "tops",
    "torment", "torments", "touch", "touches", "town", "towns",
    "trade", "trades", "train", "trains", "travel", "travels",
    "tray", "trial", "trials", "trick", "tricks",
    "trip", "trips", "troop", "troops", "trumpet", "trumpets",
    "trunk", "trunks", "trust", "trusts",
    "unity", "use", "uses", "valley", "valleys",
    "value", "values", "veil", "veils",
    "vengeance", "victory", "victories", "view", "views",
    "virgin", "virgins", "visit", "visits",
    "voice", "voices", "volume", "volumes",
    "vote", "votes", "vow", "vows", "waste", "wastes",
    "way", "ways", "weather", "weed", "weeds",
    "weight", "weights", "welfare", "west",
    "whip", "whips", "wife", "wives",
    "will", "wills", "wine", "wines",
    "wing", "wings", "winter", "winters",
    "wit", "wits", "witness", "witnesses",
    "wonder", "wonders", "wood", "woods",
    "wool", "work", "works", "world", "worlds",
    "worm", "worms", "wound", "wounds",
    "wrath", "wrong", "wrongs", "youth", "youths",
    # Additional adverbs / connectives
    "again", "aloud", "almost", "already", "although",
    "altogether", "alway", "beside", "besides",
    "early", "even", "everywhere",
    "furthermore", "hastily", "henceforth",
    "hereafter", "hereby", "heretofore",
    "hither", "hitherto", "however",
    "immediately", "instead", "itself",
    "likewise", "meanwhile", "nonetheless",
    "notwithstanding", "nowadays", "often",
    "otherwise", "perchance", "presently",
    "quickly", "quite", "scarcely", "shortly",
    "slowly", "softly", "somehow", "soon",
    "straight", "straightway", "suddenly",
    "thence", "thereafter", "therein",
    "therewith", "thither", "throughout",
    "together", "toward", "truly",
    "usually", "violently", "whereas", "whereupon",
    "yesterday", "yonder",
    # More Shakespearean archaic forms
    "afeared", "afore", "agone", "aye",
    "belike", "betide", "betime", "ere",
    "hath", "haply", "hark", "hence",
    "lest", "mayhap", "ne'er", "pray",
    "prithee", "quoth", "sooth", "thither",
    "thou", "thee", "thine", "thou'rt",
    "'twixt", "'twill", "'twixt", "whilom",
    "withal", "wot", "wist",
    # Additional contractions and short forms
    "'twill", "'tisn't", "shall't", "there's",
    "here's", "where's", "what's", "who's",
    "that's", "'twill",
    # More common prepositions and particles
    "about", "across", "along", "amongst", "athwart",
    "bearing", "concerning", "despite", "during",
    "except", "excepting", "following",
    "including", "into", "inside", "onto",
    "outside", "past", "per", "regarding",
    "since", "touching", "via",
    # Common modal / auxiliary archaic forms
    "shalt", "shouldst", "wouldst", "couldst",
    "mayst", "mightst", "durst", "dost",
    "dost", "doth", "hast", "hath",
    # Additional names commonly found in Shakespeare
    "Cassio", "Iago", "Othello", "Desdemona",
    "Hamlet", "Horatio", "Ophelia", "Polonius",
    "Lear", "Cordelia", "Goneril", "Regan",
    "Macbeth", "Banquo", "Duncan", "Malcolm",
    "Romeo", "Juliet", "Tybalt", "Mercutio",
    "Brutus", "Cassius", "Caesar", "Antony",
    "Titus", "Aaron", "Tamora", "Lavinia",
    "Timon", "Apemantus",
    "Pericles", "Marina",
    "Cymbeline", "Imogen", "Posthumus",
    "Leontes", "Perdita", "Florizel", "Hermione",
    "Page", "Ford", "Quickly", "Slender",
    # Place names
    "Verona", "Venice", "Rome", "Athens",
    "Windsor", "London", "Dover", "Troy",
    "Egypt", "France", "Britain", "Scotland",
    "Naples", "Milan", "Padua", "Mantua",
    "Syracuse", "Ephesus", "Illyria", "Navarre",
    "Tyre", "Antioch", "Cyprus",
    # Time/number modifiers
    "morrow", "morrows", "fortnight",
    "midnight", "midday", "noon",
    "dawn", "dawns", "dusk", "twilight",
    "sunrise", "sunset",
    # More emotional / descriptive vocabulary
    "pity", "passion", "glory", "misery",
    "ecstasy", "fury", "malice", "mischief",
    "venom", "spite", "rancour", "envy",
    "tears", "laughter", "smiles", "frowns",
    "hate", "hatred", "greed", "rage",
    "doubt", "doubts", "zeal", "folly",
    "bliss", "ease", "woe", "woes",
    "bale", "dole", "plight", "plights",
    # Body and ailment
    "brain", "brains", "bone", "bones",
    "flesh", "skin", "nerve", "nerves",
    "vein", "veins", "artery", "arteries",
    "pulse", "pulses", "fever", "fevers",
    "wound", "wounds", "scar", "scars",
    # Nature
    "oak", "oaks", "pine", "pines", "willow", "willows",
    "ivy", "rose", "roses", "lily", "lilies",
    "violet", "violets", "daisy", "daisies",
    "herb", "herbs", "grass", "grasses",
    "dew", "frost", "hail",
    "bird", "birds", "eagle", "eagles",
    "dove", "doves", "swan", "swans",
    "raven", "ravens", "owl", "owls",
    "lion", "lions", "tiger", "tigers",
    "wolf", "wolves", "bear", "bears",
    "hart", "harts", "deer", "dog", "dogs",
    "horse", "horses", "mare", "mares",
    "lamb", "lambs", "ewe", "ewes",
    # Common short utterances
    "ha", "ho", "hey", "pah",
    # --- Another round of commonly-appearing Shakespeare words ---
    # Verbs (present/past/participle/gerund)
    "abide", "abides", "abode",
    "account", "accounts", "accounted",
    "achieve", "achieves", "achieved",
    "accuse", "accuses", "accused",
    "admire", "admires", "admired", "admiring",
    "admit", "admits", "admitted", "admitting",
    "adore", "adores", "adored", "adoring",
    "affect", "affects", "affected",
    "afford", "affords", "afforded",
    "agree", "agrees", "agreed", "agreeing",
    "aid", "aids", "aided", "aiding",
    "aim", "aims", "aimed", "aiming",
    "alarm", "alarms", "alarmed",
    "allow", "allows", "allowed",
    "announce", "announces", "announced",
    "apply", "applies", "applied", "applying",
    "approve", "approves", "approved",
    "arrange", "arranges", "arranged",
    "arise", "arises", "arose", "arisen",
    "arouse", "arouses", "aroused",
    "arrest", "arrests", "arrested",
    "assure", "assures", "assured", "assuring",
    "attempt", "attempts", "attempted",
    "attack", "attacks", "attacked",
    "attain", "attains", "attained",
    "attend", "attends", "attended", "attending",
    "await", "awaits", "awaited",
    "award", "awards", "awarded",
    "beat", "beats", "beaten", "beating",
    "beg", "begs", "begged",
    "behave", "behaves", "behaved",
    "believe", "believes", "believed", "believing",
    "belong", "belongs", "belonged",
    "bend", "bends", "bent", "bending",
    "bestow", "bestows", "bestowed",
    "bewail", "bewails", "bewailed",
    "bite", "bites", "bit", "bitten", "biting",
    "bleed", "bleeds", "bled", "bleeding",
    "bless", "blesses", "blest", "blessing",
    "boast", "boasts", "boasted",
    "borrow", "borrows", "borrowed",
    "bow", "bows", "bowed",
    "brave", "braves", "braved",
    "breathe", "breathes", "breathed", "breathing",
    "breed", "breeds", "bred", "breeding",
    "carry", "carries", "carried", "carrying",
    "catch", "catches", "caught", "catching",
    "cease", "ceases", "ceased",
    "charge", "charges", "charged",
    "check", "checks", "checked",
    "cheer", "cheers", "cheered",
    "chide", "chides", "chid", "chidden",
    "claim", "claims", "claimed",
    "climb", "climbs", "climbed", "climbing",
    "cling", "clings", "clung",
    "close", "closes", "closed", "closing",
    "clothe", "clothes", "clothed",
    "command", "commands", "commanded", "commanding",
    "commit", "commits", "committed",
    "complain", "complains", "complained",
    "confess", "confesses", "confessed", "confessing",
    "confound", "confounds", "confounded",
    "confront", "confronts", "confronted",
    "consent", "consents", "consented",
    "contain", "contains", "contained",
    "control", "controls", "controlled",
    "convey", "conveys", "conveyed",
    "cost", "costs", "costing",
    "count", "counts", "counted",
    "cover", "covers", "covered", "covering",
    "create", "creates", "created", "creating",
    "dance", "dances", "danced", "dancing",
    "dash", "dashes", "dashed",
    "dawn", "dawns", "dawned",
    "declare", "declares", "declared",
    "defend", "defends", "defended",
    "delay", "delays", "delayed",
    "deliver", "delivers", "delivered",
    "demand", "demands", "demanded",
    "depart", "departs", "departed", "departing",
    "depend", "depends", "depended",
    "describe", "describes", "described",
    "deserve", "deserves", "deserved",
    "design", "designs", "designed",
    "destroy", "destroys", "destroyed", "destroying",
    "detect", "detects", "detected",
    "determine", "determines", "determined",
    "devise", "devises", "devised",
    "direct", "directs", "directed",
    "discover", "discovers", "discovered",
    "discuss", "discusses", "discussed",
    "disdain", "disdains", "disdained",
    "disguise", "disguises", "disguised",
    "dismiss", "dismisses", "dismissed",
    "dispute", "disputes", "disputed",
    "divide", "divides", "divided",
    "double", "doubles", "doubled",
    "drag", "drags", "dragged",
    "dread", "dreads", "dreaded",
    "drop", "drops", "dropped", "dropping",
    "earn", "earns", "earned",
    "employ", "employs", "employed",
    "endure", "endures", "endured", "enduring",
    "engage", "engages", "engaged",
    "enjoy", "enjoys", "enjoyed",
    "ensue", "ensues", "ensued",
    "enter", "enters", "entered", "entering",
    "entertain", "entertains", "entertained",
    "establish", "establishes", "established",
    "esteem", "esteems", "esteemed",
    "even", "evens", "evened",
    "examine", "examines", "examined",
    "exchange", "exchanges", "exchanged",
    "excuse", "excuses", "excused",
    "expect", "expects", "expected",
    "explain", "explains", "explained",
    "express", "expresses", "expressed",
    "extend", "extends", "extended",
    "face", "faces", "faced", "facing",
    "fade", "fades", "faded", "fading",
    "favour", "favours", "favoured",
    "feel", "feels", "felt", "feeling",
    "fetch", "fetches", "fetched", "fetching",
    "fill", "fills", "filled", "filling",
    "flee", "flees", "fled", "fleeing",
    "flood", "floods", "flooded", "flooding",
    "flourish", "flourishes", "flourished",
    "flow", "flows", "flowed",
    "fool", "fools", "fooled", "fooling",
    "force", "forces", "forced", "forcing",
    "found", "founds", "founded",
    "frame", "frames", "framed",
    "frown", "frowns", "frowned",
    "gain", "gains", "gained", "gaining",
    "gather", "gathers", "gathered", "gathering",
    "gaze", "gazes", "gazed", "gazing",
    "glance", "glances", "glanced",
    "glide", "glides", "glided",
    "glory", "glories", "gloried",
    "grace", "graces", "graced", "gracing",
    "grant", "grants", "granted", "granting",
    "greet", "greets", "greeted", "greeting",
    "groan", "groans", "groaned", "groaning",
    "guide", "guides", "guided", "guiding",
    "handle", "handles", "handled",
    "happen", "happens", "happened", "happening",
    "harm", "harms", "harmed",
    "haste", "hastes", "hasted", "hasting",
    "haunt", "haunts", "haunted", "haunting",
    "hold", "holds", "held", "holding",
    "howl", "howls", "howled", "howling",
    "hush", "hushes", "hushed",
    "inform", "informs", "informed",
    "inhabit", "inhabits", "inhabited",
    "inherit", "inherits", "inherited",
    "inquire", "inquires", "inquired",
    "insist", "insists", "insisted",
    "instruct", "instructs", "instructed",
    "intend", "intends", "intended",
    "inter", "inters", "interred",
    "intercede", "intercedes", "interceded",
    "invite", "invites", "invited",
    "invade", "invades", "invaded",
    "journey", "journeys", "journeyed",
    "kneel", "kneels", "knelt", "kneeling",
    "labour", "labours", "laboured",
    "land", "lands", "landed",
    "last", "lasts", "lasted",
    "lay", "lays", "laid", "laying",
    "lean", "leans", "leant", "leaned",
    "lie", "lies", "lay", "lain", "lying",
    "lift", "lifts", "lifted", "lifting",
    "limit", "limits", "limited",
    "list", "lists", "listed",
    "listen", "listens", "listened", "listening",
    "live", "lives", "lived", "living",
    "loathe", "loathes", "loathed", "loathing",
    "lock", "locks", "locked",
    "lodge", "lodges", "lodged",
    "long", "longs", "longed", "longing",
    "look", "looks", "looked", "looking",
    "loose", "looses", "loosed",
    "march", "marches", "marched", "marching",
    "mark", "marks", "marked",
    "marry", "marries", "married", "marrying",
    "measure", "measures", "measured",
    "meet", "meets", "met", "meeting",
    "melt", "melts", "melted",
    "mention", "mentions", "mentioned",
    "merit", "merits", "merited",
    "mind", "minds", "minded",
    "miss", "misses", "missed",
    "mount", "mounts", "mounted", "mounting",
    "move", "moves", "moved", "moving",
    "name", "names", "named", "naming",
    "neglect", "neglects", "neglected",
    "nod", "nods", "nodded",
    "note", "notes", "noted", "noting",
    "object", "objects", "objected",
    "observe", "observes", "observed",
    "obtain", "obtains", "obtained",
    "occur", "occurs", "occurred",
    "offend", "offends", "offended", "offending",
    "offer", "offers", "offered", "offering",
    "open", "opens", "opened", "opening",
    "oppose", "opposes", "opposed",
    "order", "orders", "ordered",
    "owe", "owes", "owed", "owing",
    "own", "owns", "owned", "owning",
    "pass", "passes", "passed", "passing",
    "pause", "pauses", "paused",
    "pay", "pays", "paid", "paying",
    "perform", "performs", "performed",
    "perish", "perishes", "perished",
    "persuade", "persuades", "persuaded",
    "pierce", "pierces", "pierced",
    "plant", "plants", "planted", "planting",
    "point", "points", "pointed", "pointing",
    "possess", "possesses", "possessed",
    "pour", "pours", "poured",
    "practise", "practises", "practised",
    "praise", "praises", "praised",
    "prepare", "prepares", "prepared", "preparing",
    "press", "presses", "pressed",
    "prevent", "prevents", "prevented",
    "proceed", "proceeds", "proceeded",
    "proclaim", "proclaims", "proclaimed",
    "procure", "procures", "procured",
    "produce", "produces", "produced",
    "profess", "professes", "professed",
    "promise", "promises", "promised", "promising",
    "pronounce", "pronounces", "pronounced",
    "propose", "proposes", "proposed",
    "protect", "protects", "protected",
    "protest", "protests", "protested",
    "prove", "proves", "proved", "proving",
    "provide", "provides", "provided",
    "pull", "pulls", "pulled", "pulling",
    "punish", "punishes", "punished",
    "purchase", "purchases", "purchased",
    "pursue", "pursues", "pursued",
    "push", "pushes", "pushed",
    "quarrel", "quarrels", "quarrelled",
    "quit", "quits", "quitted",
    "quote", "quotes", "quoted",
    "raise", "raises", "raised", "raising",
    "reach", "reaches", "reached", "reaching",
    "realise", "realises", "realised",
    "receive", "receives", "received", "receiving",
    "regard", "regards", "regarded", "regarding",
    "reign", "reigns", "reigned",
    "rejoice", "rejoices", "rejoiced", "rejoicing",
    "relate", "relates", "related",
    "release", "releases", "released",
    "relieve", "relieves", "relieved",
    "remain", "remains", "remained", "remaining",
    "repair", "repairs", "repaired",
    "repeat", "repeats", "repeated",
    "repent", "repents", "repented", "repenting",
    "reply", "replies", "replied",
    "report", "reports", "reported",
    "require", "requires", "required",
    "resist", "resists", "resisted",
    "resolve", "resolves", "resolved", "resolving",
    "respect", "respects", "respected",
    "rest", "rests", "rested", "resting",
    "retire", "retires", "retired",
    "reveal", "reveals", "revealed",
    "revenge", "revenges", "revenged", "revenging",
    "reverse", "reverses", "reversed",
    "reward", "rewards", "rewarded",
    "ride", "rides", "rode", "ridden", "riding",
    "rouse", "rouses", "roused", "rousing",
    "rule", "rules", "ruled", "ruling",
    "save", "saves", "saved", "saving",
    "scatter", "scatters", "scattered",
    "seal", "seals", "sealed",
    "search", "searches", "searched", "searching",
    "seat", "seats", "seated",
    "seize", "seizes", "seized",
    "serve", "serves", "served", "serving",
    "settle", "settles", "settled", "settling",
    "shape", "shapes", "shaped",
    "share", "shares", "shared",
    "shed", "sheds", "shedding",
    "shine", "shines", "shone", "shined", "shining",
    "shout", "shouts", "shouted",
    "shoot", "shoots", "shot", "shooting",
    "shrink", "shrinks", "shrank", "shrunk", "shrinking",
    "smell", "smells", "smelt", "smelled",
    "smile", "smiles", "smiled", "smiling",
    "smite", "smites", "smote", "smitten",
    "smooth", "smooths", "smoothed",
    "snatch", "snatches", "snatched",
    "soften", "softens", "softened",
    "spare", "spares", "spared", "sparing",
    "speak", "speaks", "spoke", "spoken", "speaking",
    "spit", "spits", "spat", "spitting",
    "split", "splits", "splitting",
    "spoil", "spoils", "spoiled", "spoilt",
    "spread", "spreads", "spreading",
    "spring", "springs", "sprang", "sprung",
    "squeeze", "squeezes", "squeezed",
    "stain", "stains", "stained",
    "start", "starts", "started", "starting",
    "state", "states", "stated",
    "stay", "stays", "stayed", "staying",
    "stick", "sticks", "stuck",
    "stir", "stirs", "stirred", "stirring",
    "stoop", "stoops", "stooped",
    "strain", "strains", "strained",
    "stretch", "stretches", "stretched",
    "strike", "strikes", "struck", "striking",
    "stroke", "strokes", "stroked",
    "struggle", "struggles", "struggled",
    "subdue", "subdues", "subdued",
    "succeed", "succeeds", "succeeded",
    "suffer", "suffers", "suffered", "suffering",
    "suggest", "suggests", "suggested",
    "suit", "suits", "suited", "suiting",
    "supply", "supplies", "supplied",
    "support", "supports", "supported",
    "suppose", "supposes", "supposed",
    "suspect", "suspects", "suspected",
    "sustain", "sustains", "sustained",
    "sway", "sways", "swayed",
    "swell", "swells", "swelled", "swollen",
    "swim", "swims", "swam", "swum", "swimming",
    "swing", "swings", "swung", "swinging",
    "take", "takes", "took", "taken", "taking",
    "teach", "teaches", "taught", "teaching",
    "tell", "tells", "told", "telling",
    "tempt", "tempts", "tempted",
    "tend", "tends", "tended", "tending",
    "thank", "thanks", "thanked", "thanking",
    "thrive", "thrives", "throve", "thriven",
    "thrust", "thrusts", "thrusting",
    "torment", "torments", "tormented",
    "touch", "touches", "touched", "touching",
    "tread", "treads", "trod", "trodden",
    "treat", "treats", "treated", "treating",
    "tremble", "trembles", "trembled", "trembling",
    "trust", "trusts", "trusted",
    "turn", "turns", "turned", "turning",
    "understand", "understands", "understood",
    "undertake", "undertakes", "undertook",
    "unfold", "unfolds", "unfolded",
    "urge", "urges", "urged", "urging",
    "use", "uses", "used", "using",
    "vanish", "vanishes", "vanished", "vanishing",
    "venture", "ventures", "ventured",
    "visit", "visits", "visited", "visiting",
    "vow", "vows", "vowed", "vowing",
    "wait", "waits", "waited", "waiting",
    "wander", "wanders", "wandered", "wandering",
    "warn", "warns", "warned", "warning",
    "waste", "wastes", "wasted", "wasting",
    "watch", "watches", "watched", "watching",
    "weave", "weaves", "wove", "woven",
    "welcome", "welcomes", "welcomed",
    "whip", "whips", "whipped",
    "whirl", "whirls", "whirled",
    "whisper", "whispers", "whispered", "whispering",
    "wield", "wields", "wielded",
    "wipe", "wipes", "wiped",
    "witness", "witnesses", "witnessed",
    "worry", "worries", "worried",
    "worship", "worships", "worshipped",
    "wound", "wounds", "wounded", "wounding",
    "yield", "yields", "yielded", "yielding",
)

# Build a trie: prefix -> {next_char: count}
# A "count" is a small integer used to derive bias magnitude.
_TRIE: dict[str, dict[str, int]] = {}


def _add_word(word: str) -> None:
    for i in range(len(word) + 1):
        prefix = word[:i]
        _TRIE.setdefault(prefix, {})
        if i < len(word):
            nxt = word[i]
            _TRIE[prefix][nxt] = _TRIE[prefix].get(nxt, 0) + 1
        else:
            # Word terminator: plausible next chars are space, newline,
            # or punctuation.
            for term, weight in (
                (" ", 3), (",", 2), (".", 2), (";", 1), (":", 1),
                ("!", 1), ("?", 1), ("\n", 2), ("'", 1),
            ):
                _TRIE[prefix][term] = _TRIE[prefix].get(term, 0) + weight


for _w in _WORDS:
    _add_word(_w)


# --- Algorithmic expansion of archaic Shakespearean inflections ---
#
# Shakespeare very frequently uses archaic -eth, -est (second-person),
# and 'd contracted past-tense forms of common verbs. Rather than hand-
# listing every inflection, we generate them from a small set of base
# verbs. The generation uses only English orthography rules — no corpus
# statistics. The added surface forms help BPC (many of these appear
# in the training text and previously went off-trie) and help sampling
# stay in archaic idiom.
_ARCHAIC_VERB_BASES: tuple[str, ...] = (
    "speak", "think", "know", "see", "say", "make", "take", "give",
    "hold", "find", "tell", "hear", "keep", "leave", "bring", "stand",
    "let", "set", "run", "come", "go", "love", "hate", "live", "die",
    "lie", "rise", "fall", "seem", "feel", "wait", "wish", "need",
    "want", "look", "pray", "show", "bear", "turn", "work", "call",
    "play", "swear", "follow", "serve", "enter", "answer", "suffer",
    "depart", "remain", "return", "believe", "become", "grow", "appear",
    "remember", "forget", "attend", "command", "consider", "perceive",
    "request", "obey", "intend", "mark", "deserve", "permit",
    "approach", "receive", "behold",
)


def _apply_archaic_inflection(base: str) -> list[str]:
    """Return plausible -eth, -est, -'st, and -'d forms for a base verb.

    Spelling rules are approximations consistent with Early Modern
    English orthography:
      - base ending in 'e':  love → loveth, lovest, lov'st, lov'd
      - base ending in consonant after short vowel: run → runneth? (no,
        use runs instead). We handle only regular cases — irregulars
        are better covered by the _WORDS list already.
      - base ending in 'y' after consonant: cry → crieth, criest?
        (Skip -y bases: they're irregular.)
      - others: speak → speaketh, speakest, speak'st, speak'd
    """
    forms: list[str] = []
    if base.endswith("e"):
        stem = base[:-1]
        forms.extend([base + "th", base + "st", stem + "'st", stem + "'d"])
    elif base.endswith("y"):
        # Skip -y stems; too much spelling variance.
        pass
    else:
        forms.extend([base + "eth", base + "est", base + "'st", base + "'d"])
    return forms


for _base in _ARCHAIC_VERB_BASES:
    for _form in _apply_archaic_inflection(_base):
        _add_word(_form)


# Set of exact words (lowercased) — used by predict to apply an
# additional terminator boost when the buffer matches a complete known
# word, regardless of whether the word is also a prefix of other words.
COMPLETE_WORDS: frozenset[str] = frozenset(w.lower() for w in _WORDS)


def _bias_for(prefix: str) -> list[float] | None:
    """Return a VOCAB_SIZE-length bias vector (or None if no matching
    prefix) that boosts next chars consistent with completing a known
    word. The bias scale grows with the prefix length.
    """
    if prefix not in _TRIE:
        return None
    nexts = _TRIE[prefix]
    if not nexts:
        return None
    import math
    n = len(prefix)
    # Scale: how strongly we believe the prefix implies a known word.
    # Too strong on short prefixes would overfit to our word list; so we
    # ramp up aggressively with length.
    scale = min(-0.2 + 0.4 * n, 2.0)
    total = sum(nexts.values())
    vec = [0.0] * VOCAB_SIZE
    # Also apply a negative bump to *all* letters so that unlisted
    # continuations are gently penalized. The training corpus contains
    # countless words not in our list, so the bump must be gentle.
    negative_bump = -0.7 * min(scale, 2.0)
    for ch in "abcdefghijklmnopqrstuvwxyz":
        if ch in VOCAB_INDEX:
            vec[VOCAB_INDEX[ch]] = negative_bump
    # Boost listed continuations by log-ratio against uniform.
    for ch, w in nexts.items():
        if ch not in VOCAB_INDEX:
            continue
        frac = w / total
        # log-ratio against a baseline of 0.05 — treats frac 0.05 as
        # neutral, larger fracs as boosts.
        bias = scale * math.log((frac + 0.02) / 0.05)
        vec[VOCAB_INDEX[ch]] = bias
        if ch.isalpha():
            up = ch.upper()
            if up in VOCAB_INDEX:
                vec[VOCAB_INDEX[up]] = bias * 0.3
    return vec


# Precompute bias vectors for every prefix in the trie. Keeps predict
# fast: just a dict lookup.
def _precompute() -> dict[str, list[float]]:
    out: dict[str, list[float]] = {}
    for prefix in _TRIE:
        v = _bias_for(prefix)
        if v is not None:
            out[prefix] = v
    return out


PREFIX_BIAS: dict[str, list[float]] = _precompute()


def word_trie_bias(buffer: str) -> list[float] | None:
    """Return a bias vector for the current partial-word buffer, or None."""
    if not buffer:
        return None
    if buffer in PREFIX_BIAS:
        return PREFIX_BIAS[buffer]
    return None


def is_on_trie(buffer: str) -> bool:
    return bool(buffer) and buffer in PREFIX_BIAS


# A "force-end" bias vector: when the current word buffer has drifted
# off the trie of known words, this strongly boosts word-terminating
# characters (space, newline, punctuation) to end the gibberish ASAP.
def _build_force_end() -> list[float]:
    vec = [0.0] * VOCAB_SIZE
    for ch, bias in (
        (" ", 2.2),
        ("\n", 1.2),
        (",", 1.3),
        (".", 1.0),
        (";", 0.7),
        (":", 0.5),
        ("!", 0.6),
        ("?", 0.6),
        ("'", 0.4),
    ):
        if ch in VOCAB_INDEX:
            vec[VOCAB_INDEX[ch]] = bias
    # Small negative on letters (encourage ending).
    for ch in "abcdefghijklmnopqrstuvwxyz":
        if ch in VOCAB_INDEX:
            vec[VOCAB_INDEX[ch]] = -0.3
    for ch in "ABCDEFGHIJKLMNOPQRSTUVWXYZ":
        if ch in VOCAB_INDEX:
            vec[VOCAB_INDEX[ch]] = -0.4
    return vec


FORCE_END_BIAS: list[float] = _build_force_end()

